name = "jsreact"
compatibility_date = "2024-01-01"
main = "dist/index.html"

[site]
bucket = "./dist"

[build]
command = "npm run pages:build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { NODE_VERSION = "18", NPM_VERSION = "9" } 