name = "image-host"
main = "image-host.js"
compatibility_date = "2024-03-25"

# Configure your KV namespace
[[kv_namespaces]]
binding = "IMAGES"
id = "78167fde4bd24621b439d33dbd027c49"

# Configure CORS and other security headers
[vars]
ALLOWED_ORIGINS = "*"

# Configure resource limits
[limits]
memory_mb = 128
uploads_size_mb = 25
cpu_ms = 50
