on:
  push:
    branches: [cfpages]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Generate Sitemap, Commit, and Deploy
    permissions:
      contents: write

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: generate-sitemap
      uses: cicirello/generate-sitemap@v1.10.1
      with:
        path-to-root: .
        input-paths: dist
        base-url-path: https://jsreact.com
        include-html: true
        include-pdf: true
        sitemap-format: xml
        additional-extensions: ""
        drop-html-extension: false
        date-only: false
        exclude-paths: ""

    - name: Output stats
      if: steps.sitemap.outputs.sitemap-path # Only execute if sitemap generation succeeded
      run: |
        echo "Sitemap Path: ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "URL Count: ${{ steps.sitemap.outputs.url-count }}"
        echo "Excluded Count: ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        if [[ $(git diff --stat --staged) != '' ]]; then
          git commit -m "Add generated sitemap"
          git push
        fi

    - name: Deploy
      if: success()
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
