on:
  push:
    branches: [ rollback ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.10.0
      with:
        path-to-root: "./src" # The path to the root of the website
        base-url-path: https://jsreact.com # The url of your webpage
        include-html: true # Indicates whether to include html files in the sitemap.
        include-pdf: true # Indicates whether to include pdf files in the sitemap.
        sitemap-format: xml # Indicates if sitemap should be formatted in xml.
        additional-extensions: "" # Space separated list of additional file extensions to include in sitemap.
        drop-html-extension: false # Enables dropping .html from urls in sitemap.
        date-only: false # Pass true to include only the date without the time in XML sitemaps; and false to include full date and time.
        exclude-paths: "" # Space separated list of paths to exclude from the sitemap.

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ $(git diff --stat --staged) != '' ]]; then
          git commit -m "Add generated sitemap"
          git push
        fi
