on:
  push:
    branches: [cfpages]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build, Test, Generate Sitemap, and Deploy

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.10.0
      with:
        path-to-root: ./src
        base-url-path: https://jsreact.com
        include-html: true
        include-pdf: true
        sitemap-format: xml
        additional-extensions: ""
        drop-html-extension: false
        date-only: false
        exclude-paths: ""

    - name: Output stats
      if: steps.sitemap.outputs.sitemap-path # Only execute if sitemap generation succeeded
      run: |
        echo "Sitemap Path: ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "URL Count: ${{ steps.sitemap.outputs.url-count }}"
        echo "Excluded Count: ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ $(git diff --stat --staged) != '' ]]; then
          git commit -m "Add generated sitemap"
          git push

    - name: Deploy
      if: success()
      run: npm run deploy
